config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    include PgSearch::Model 

    pg_search_scope :search_full_text,
    against: {
        username: 'A',
        description: 'B',
        id: 'C',
    },
    using: {
        tsearch: {
            prefix: true,
            any_word: true,
            dictionary: "spanish"  
        }
    } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    Pagy::DEFAULT[:items] = 10
    include Pagy::Backend   

    require 'pagy/extras/bootstrap'
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets or /tweets.json
  def index
    @pagy, @tweets = pagy(Tweet.all.order(:username))

    if params[:query_text].present?
      @pagy, @tweets = pagy(Tweet.search_full_text(params[:query_text]))
    end
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweet_url(@tweet), notice: "Creado con exito.", class:"mensajes" }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "Actualizado con exito." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Borrado con exito." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:description, :username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Clon</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css">

<body style="background-color: rgb(0, 0, 0)" class="container">
  <div id="contenido">
    <%= yield %>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

app/views/tweets/_buscador.html.erb
                <div class="abajo fijo">
                    <%= form_with url: tweets_path, method: :get do |form| %>
                    <h1 class="decoration mb-3">Buscador</h1>
                    <%= form.text_field :query_text, value: params[:query_text],class: "color mb-4" %>
                    <%= form.submit "Buscar", class:"boton decoration" %>
                    <% end %>
                </div>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block", class:"decoration" %>
    <%= form.text_field :username %>
  </div>


  <div>
    <%= form.label :description, style: "display: block", class:"decoration" %>
    <%= form.text_area :description, style: "width: 500px; height: 150px; overflow: auto;"%>
  </div>


  <div>
    <%= form.submit "Publicar Tweet", class: "boton decoration mt-4"%>
  </div>
<% end %>

app/views/tweets/_navbar.html.erb
        <section class="izquierda fijo">
            <header>
                <div>
                    <ul>
                        <li>
                            <a class="navbar-link no-decoration" href="/"><i class="fa-brands fa-twitter"
                                    style="color: #ffffff; left"></i></a>
                        </li>
                        <li>
                            <a class="navbar-link no-decoration" href="/"><i class="fa-solid fa-house"
                                    style="color: #ffffff;"></i>Inicio</a>
                        </li>
                        <li>
                            <a class="navbar-link no-decoration" href="#"><i class="fa-regular fa-hashtag"
                                    style="color: #ffffff;"></i> Explorar</a><%= render "buscador", tweet: @tweet%>
                        </li>
                        <li>
                            <button type="button" class="boton no-decoration mt-5"><a class="navbar-link no-decoration"
                                    href="/tweets/new"> Twittear</a></button>
                        </li>
                    </ul>
                </div>
            </header>
        </section>

app/views/tweets/_navbar2.html.erb
        <section class="izquierda fijo">
            <header>
                <div>
                    <ul>
                        <li>
                            <a class="navbar-link no-decoration" href="/"><i class="fa-brands fa-twitter"
                                    style="color: #ffffff; left"></i></a>
                        </li>
                        <li>
                            <a class="navbar-link no-decoration" href="/"><i class="fa-solid fa-house"
                                    style="color: #ffffff;"></i>Inicio</a>
                        </li>
                        <li>
                            <a class="navbar-link no-decoration" href="/"><i class="fa-regular fa-hashtag"
                                    style="color: #ffffff;"></i> Explorar</a>
                        </li>
                        <li>
                            <button type="button" class="boton no-decoration mt-5"><a class="navbar-link no-decoration"
                                    href="/tweets/new"> Twittear</a></button>
                        </li>
                    </ul>
                </div>
            </header>
        </section>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>" class="mb-5 container">
  <div class="p-4">
    <p>
      <strong class= "decoration">Username:</strong>
      <span class="decoration"><%= tweet.username%></span>
    </p>

    <p>
      <strong  class= "decoration">Description:</strong>
      <span class="decoration"><%= tweet.description%></span>
    </p>
  </div>
</div>

app/views/tweets/edit.html.erb
<%= render "navbar2", tweet: @tweet %>
<h1 class="no-decoration">Editar Tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div class="decoration mt-3">
  <%= link_to "Mostrar tweet", @tweet, class:"boton decoration" %>  <%= link_to "Volver a los tweets", tweets_path, class:"boton decoration" %>
</div>

app/views/tweets/index.html.erb
<%= render "navbar", tweet: @tweet %>



<p style="color: green"><%= notice %></p>


<div class="centrar">

  <div id="tweets">
    <h1 class="no-decoration">Tweets</h1>
    <% @tweets.each do |tweet| %>
    <div class="bordertweets">
      <%= render tweet %>
      <p><%= link_to "Mostrar este tweet", tweet, class: "boton decoration margen"%></p>
    </div>
    <% end %>
    <div class="mt-4">
      <%== pagy_bootstrap_nav(@pagy) %>
    </div>
  </div>
<div>

app/views/tweets/new.html.erb
<%= render "navbar2", tweet: @tweet %>
<h1 class="no-decoration">Publicar tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Volver a los tweets", tweets_path, class: "boton decoration" %>
</div>

app/views/tweets/show.html.erb
<%= render "navbar2", tweet: @tweet %>
<p style="color: green"><%= notice %></p>
<div class="container bordertweets">
  <%= render @tweet %>
</div>

  <div id= "elecciontweet" class="row">
    <div class="col-4">
      <%= link_to "Editar", edit_tweet_path(@tweet), class:"boton decoration" %>
    </div>
    <div class="col-4">
      <%= button_to "Borrar", @tweet, method: :delete, class:"boton decoration" %>
    </div>
    <div class="col-4">
      <%= link_to "Volver a los tweets", tweets_path, class:"boton decoration" %>
    </div>
  </div>